platform :ios, '7.0'

pod 'Ono'
pod 'CDYObjectModel', :git => 'https://github.com/coodly/CDYObjectModel.git'
pod 'AFNetworking'
pod 'MRProgress'
pod 'JCSFoundation/UserInput', :git => 'https://github.com/jaanussiim/JCSFoundation.git'
#pod 'JCSFoundation/UserInput', :path => '../JCSFoundation'
pod 'JCSFoundation/CoreData', :git => 'https://github.com/jaanussiim/JCSFoundation.git'
#pod 'CDYImagesRetrieve', :path => '../CDYImagesRetrieve'
pod 'CDYImagesRetrieve', :git => 'https://github.com/coodly/CDYImagesRetrieve.git'
#pod 'CDYImageScale', :path => '../CDYImageScale'
pod 'CDYImageScale', :git => 'https://github.com/coodly/CDYImageScale.git'